Update jpeg-1-check

diff --git a/scripts/jpeg-1-check b/scripts/jpeg-1-check
--- a/scripts/jpeg-1-check
+++ b/scripts/jpeg-1-check
@@ -1,11 +1,10 @@
 #!/bin/sh
 #Check exif photos in gdrive/photos/ directory
 clear
-
+if ! -f /usr/bin/exiv2 ; then pushbullet push all note "Rasperry Pi" "ERROR: Please install exiv2"; exit; fi
 rm -rf /media/hdd/Drive/Photos/*
 cd /media/hdd/Drive/
-drive pull --quiet Photos
-if [ ! -f /usr/bin/exiv2 ]; then pushbullet push all note "Rasperry Pi" "ERROR: Please install exiv2"; exit; fi
+if ! drive pull --quiet Photos ; then pushbullet push all note "ERROR DRIVE" "ERROR PULL DRIVE"; exit; fi
 
 find /media/hdd/Drive/Photos -iname "*.jpg" -type f | sort | while read FILE ; do 
 EXIF=`exiv2 "$FILE" 2> null | grep "Image timestamp" | cut -d ' ' -f 4 | tr ':' '-'`
@@ -29,6 +28,6 @@ DAT=`echo "$(dirname "$FILE")" | rev | cut -d '/' -f 1 | rev | cut -d ' ' -f  1 
 printf "\033[00m$FILE\n\033[01mEXIF1 : EXIF : $EXIF $EXIF1 EXIF2 : $EXIF2 DATE : $DAT\n"
 done
 
-drive push --quiet Photos
+if ! drive push --quiet Photos ; then pushbullet push all note "ERROR DRIVE" "ERROR PUSH DRIVE"; exit; fi
 
 pushbullet push all note "Rasperry Pi" "Please control the Starred Files in Drive and run next script"
